#!/usr/bin/env python3
import os

BASE = "/home/ega/Escritorio/COLIBRI_DIGITAL"

# 91 books matching LIBRO_MAP in routes.py
LIBROS = [
    (1, "LGA-HTML5", "HTML5: El Lenguaje de la Web", "Libro completo de HTML5 desde cero hasta avanzado.", "programacion"),
    (2, "LGA-CSS3", "CSS3: Diseño y Estilo Web", "Domina CSS3: Flexbox, Grid, Animaciones y más.", "programacion"),
    (3, "LGA-JS", "JavaScript: De Cero a Experto", "El manual definitivo de JavaScript.", "programacion"),
    (4, "LGA-TS", "TypeScript: Tipado Avanzado", "JavaScript con tipos para proyectos profesionales.", "programacion"),
    (5, "LGA-REACT", "React: Aplicaciones Modernas", "Construye aplicaciones web con React 18.", "programacion"),
    (6, "LGA-NODE", "Node.js: Backend Moderno", "JavaScript en el servidor con Node.js.", "programacion"),
    (7, "LGA-PHP", "PHP: Web Dinámica", "Desarrollo backend con PHP moderno.", "programacion"),
    (8, "LGA-SQL", "SQL: Bases de Datos", "Domina SQL y bases de datos relacionales.", "programacion"),
    (9, "LGA-PYTHON", "Python: Automatización y Más", "Python aplicado a tareas del mundo real.", "programacion"),
    (10, "LGA-JAVA", "Java: Enterprise", "Desarrollo empresarial con Java.", "programacion"),
    (11, "LGA-C", "C: Programación de Sistemas", "Lenguaje C para sistemas y embebidos.", "programacion"),
    (12, "LGA-CPP", "C++: Alto Rendimiento", "Programación orientada a objetos con C++.", "programacion"),
    (13, "LGA-CSHARP", "C#: .NET Ecosystem", "Desarrollo .NET con C#.", "programacion"),
    (14, "LGA-GO", "Go: Concurrencia", "Lenguaje Go para microservicios.", "programacion"),
    (15, "LGA-RUBY", "Ruby: Elegante y Productivo", "Desarrollo web ágil con Ruby.", "programacion"),
    (16, "LGA-IA", "Introducción a la Inteligencia Artificial", "Fundamentos de IA, Machine Learning y LLMs.", "ia"),
    (17, "LGA-DJANGO", "Django: Web sin Complicaciones", "Desarrollo web rápido con Python.", "programacion"),
    (18, "LGA-DOCKER", "Docker: Contenedores", "Despliega aplicaciones con Docker.", "devops"),
    (19, "LGA-GIT", "Git y GitHub", "Control de versiones y trabajo colaborativo.", "devops"),
    (20, "LGA-API", "APIs RESTful", "Diseño y construcción de APIs profesionales.", "programacion"),
    (21, "LGA-SEGURIDAD", "Seguridad Web", "Protege tus aplicaciones web.", "seguridad"),
    (22, "LGA-LINUX", "Linux para Desarrolladores", "La terminal y el ecosistema Linux.", "devops"),
    (23, "LGA-ARQUITECTURA", "Arquitectura de Software", "Patrones de diseño y buenas prácticas.", "programacion"),
    (24, "LGA-LIDERAZGO", "Liderazgo Tecnológico", "De desarrollador a líder de equipo.", "carrera"),
    (25, "LGA-VSCODE", "VS Code Profesional", "El editor que todo desarrollador debe dominar.", "herramientas"),
    (26, "LGA-TERMINAL", "Terminal Linux", "Domina la línea de comandos.", "herramientas"),
    (27, "LGA-REDES", "Redes de Computadoras", "Fundamentos y administración de redes.", "infraestructura"),
    (28, "LGA-BP", "Buenas Prácticas de Programación", "Código limpio y desarrollo profesional.", "programacion"),
    (29, "LGA-GITAV", "Git Avanzado", "Control de versiones profesional.", "devops"),
    (30, "LGA-TYPESCRIPT", "TypeScript Avanzado", "Tipos genéricos, decoradores y patrones.", "programacion"),
    (31, "LGA-VUE", "Vue.js: Framework Progresivo", "Aplicaciones web modernas con Vue.js 3.", "programacion"),
    (32, "LGA-ANGULAR", "Angular: Framework Empresarial", "Aplicaciones empresariales con Angular.", "programacion"),
    (33, "LGA-BOOTSTRAP", "Bootstrap 5: CSS Framework", "Diseño responsivo rápido con Bootstrap.", "programacion"),
    (34, "LGA-TAILWIND", "Tailwind CSS: Utility-First", "Diseño moderno con Tailwind CSS.", "programacion"),
    (35, "LGA-EXPRESS", "Express.js: Backend Node.js", "APIs y servidores con Express.js.", "programacion"),
    (36, "LGA-LARAVEL", "Laravel: PHP Framework", "Desarrollo web profesional con Laravel.", "programacion"),
    (37, "LGA-FLASK", "Flask: Python Microframework", "APIs ligeras con Flask y Python.", "programacion"),
    (38, "LGA-SPRING", "Spring Boot: Java Framework", "Aplicaciones empresariales con Spring Boot.", "programacion"),
    (39, "LGA-ASPNET", "ASP.NET Core: .NET Framework", "Desarrollo web con ASP.NET Core.", "programacion"),
    (40, "LGA-GRAPHQL", "GraphQL: API Moderna", "Consultas flexibles con GraphQL.", "programacion"),
    (41, "LGA-MICROSVC", "Microservicios: Arquitectura", "Arquitectura de microservicios distribuida.", "programacion"),
    (42, "LGA-AUTH", "Autenticación y Seguridad", "OAuth, JWT y seguridad profesional.", "seguridad"),
    (43, "LGA-MYSQL", "MySQL: Base de Datos", "Administración y optimización de MySQL.", "datos"),
    (44, "LGA-POSTGRES", "PostgreSQL: BD Avanzada", "Base de datos relacional avanzada.", "datos"),
    (45, "LGA-MONGODB", "MongoDB: NoSQL", "Base de datos documental con MongoDB.", "datos"),
    (46, "LGA-REDIS", "Redis: Caché y Sesiones", "Base de datos en memoria con Redis.", "datos"),
    (47, "LGA-FIREBASE", "Firebase: Backend como Servicio", "Backend sin servidor con Firebase.", "backend"),
    (48, "LGA-RUST", "Rust: Sistemas Seguros", "Programación de sistemas con Rust.", "programacion"),
    (49, "LGA-KOTLIN", "Kotlin: Moderno y Conciso", "Desarrollo moderno con Kotlin.", "programacion"),
    (50, "LGA-SWIFT", "Swift: iOS y macOS", "Desarrollo de apps Apple con Swift.", "mobile"),
    (51, "LGA-DART", "Dart: Lenguaje Moderno", "El lenguaje detrás de Flutter.", "programacion"),
    (52, "LGA-POO", "POO: Programación Orientada a Objetos", "Paradigma de objetos desde cero.", "programacion"),
    (53, "LGA-ALGORITMOS", "Algoritmos y Estructuras", "Algoritmos, complejidad y optimización.", "programacion"),
    (54, "LGA-ANDROID", "Android: Apps Nativas", "Desarrollo de aplicaciones Android.", "mobile"),
    (55, "LGA-FLUTTER", "Flutter: Multiplataforma", "Apps nativas multiplataforma con Flutter.", "mobile"),
    (56, "LGA-RN", "React Native: Mobile", "Apps móviles con React Native.", "mobile"),
    (57, "LGA-PROMPT", "Prompt Engineering", "Ingeniería de prompts para IA generativa.", "ia"),
    (58, "LGA-OPENAI", "OpenAI API", "Integración con GPT, DALL-E y Whisper.", "ia"),
    (59, "LGA-GEMINI", "Gemini AI", "Modelos multimodales de Google DeepMind.", "ia"),
    (60, "LGA-CLAUDE", "Claude AI", "IA conversacional con Claude de Anthropic.", "ia"),
    (61, "LGA-RAG", "RAG: Generación Aumentada", "Búsqueda + generación de texto con RAG.", "ia"),
    (62, "LGA-AGENTES", "Agentes IA", "Automatización inteligente con agentes.", "ia"),
    (63, "LGA-REDES-SEC", "Seguridad en Redes", "Protección de infraestructura de red.", "seguridad"),
    (64, "LGA-PENTEST", "Pentesting Profesional", "Pruebas de penetración y ethical hacking.", "seguridad"),
    (65, "LGA-AWS", "AWS: Cloud Computing", "Infraestructura en la nube con AWS.", "cloud"),
    (66, "LGA-AZURE", "Azure: Microsoft Cloud", "Servicios cloud con Microsoft Azure.", "cloud"),
    (67, "LGA-GCP", "GCP: Google Cloud", "Infraestructura cloud con Google Cloud.", "cloud"),
    (68, "LGA-K8S", "Kubernetes: Orquestación", "Orquestación de contenedores con K8s.", "devops"),
    (69, "LGA-DEVOPS", "DevOps: Integración", "CI/CD, automatización y cultura DevOps.", "devops"),
    (70, "LGA-UNITY", "Unity: Videojuegos", "Desarrollo de juegos 2D/3D con Unity.", "juegos"),
    (71, "LGA-UNREAL", "Unreal Engine", "Juegos AAA con Unreal Engine 5.", "juegos"),
    (72, "LGA-GODOT", "Godot: Game Engine", "Desarrollo de juegos con Godot.", "juegos"),
    (73, "LGA-IA-JUEGOS", "IA en Videojuegos", "Inteligencia artificial para juegos.", "juegos"),
    (74, "LGA-ARDUINO", "Arduino: Electrónica", "Prototipado electrónico con Arduino.", "iot"),
    (75, "LGA-RPI", "Raspberry Pi", "Computación física con Raspberry Pi.", "iot"),
    (76, "LGA-IOT", "IoT: Internet de las Cosas", "Dispositivos conectados y sensores.", "iot"),
    (77, "LGA-PANDAS", "Pandas: Data Science", "Análisis de datos con Python Pandas.", "datos"),
    (78, "LGA-POWERBI", "Power BI: Visualización", "Dashboards y BI con Power BI.", "datos"),
    (79, "LGA-BIGDATA", "Big Data: Procesamiento", "Procesamiento masivo de datos.", "datos"),
    (80, "LGA-PROY-N1", "Proyecto N1: Portafolio Web", "Construye tu portafolio profesional.", "proyectos"),
    (81, "LGA-PROY-N2", "Proyecto N2: E-commerce", "Tienda online completa.", "proyectos"),
    (82, "LGA-PROY-N3", "Proyecto N3: Red Social", "Red social con autenticación.", "proyectos"),
    (83, "LGA-PROY-N4", "Proyecto N4: Dashboard", "Panel de control con datos reales.", "proyectos"),
    (84, "LGA-PROY-N5", "Proyecto N5: API REST", "API RESTful completa.", "proyectos"),
    (85, "LGA-PROY-N6", "Proyecto N6: App Mobile", "Aplicación móvil completa.", "proyectos"),
    (86, "LGA-PROY-N7", "Proyecto N7: IA Predictiva", "Modelo de machine learning.", "proyectos"),
    (87, "LGA-PROY-N8", "Proyecto N8: IoT", "Sistema IoT completo.", "proyectos"),
    (88, "LGA-PROY-N9", "Proyecto N9: Juego 2D", "Videojuego completo.", "proyectos"),
    (89, "LGA-PROY-N10", "Proyecto N10: SaaS", "Software como servicio.", "proyectos"),
    (90, "LGA-PROY-N11", "Proyecto N11: Blockchain", "Aplicación descentralizada.", "proyectos"),
    (91, "LGA-PROY-N12", "Proyecto N12: Full Stack", "Aplicación full stack completa.", "proyectos"),
]

PRICE_MAP = {
    "programacion": (399, 199, 299, 499, 799),
    "ia":          (599, 299, 399, 699, 999),
    "devops":      (449, 219, 329, 549, 849),
    "seguridad":   (449, 219, 329, 549, 849),
    "carrera":     (349, 179, 249, 449, 699),
    "herramientas":(349, 179, 249, 449, 699),
    "infraestructura":(449, 219, 329, 549, 849),
    "datos":       (449, 219, 329, 549, 849),
    "backend":     (449, 219, 329, 549, 849),
    "mobile":      (449, 219, 329, 549, 849),
    "cloud":       (549, 269, 379, 649, 949),
    "juegos":      (499, 249, 349, 599, 899),
    "iot":         (449, 219, 329, 549, 849),
    "proyectos":   (299, 149, 199, 399, 599),
}

lines = ["INSERT OR IGNORE INTO productos (id, sku, titulo, descripcion, division_id, categoria, precio_fisico, precio_pdf, precio_audio, precio_video, precio_premium, autor, activo) VALUES"]
for i, (lid, sku, titulo, descripcion, cat) in enumerate(LIBROS):
    pf, pp, pa, pv, px = PRICE_MAP.get(cat, (399, 199, 299, 499, 799))
    comma = "," if i < len(LIBROS) - 1 else ";"
    lines.append(f"({lid},'{sku}','{titulo}','{descripcion}','academia','{cat}',{pf},{pp},{pa},{pv},{px},'Esteban Gutiérrez',1){comma}")

with open(os.path.join(BASE, "seed_productos.sql"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Seed generado: {len(LIBROS)} productos")
